### ISSUE TITLE
Using GAN_BERT for french data

### ISSUE THREAD

**Issue by keloemma** [louisowen6/GAN_BERT_CLINC150#1]
Hello,

I am interested in knowing if it is possible to use your code but for french Data. I would like to generate text for further using them in a classification task. And I was wondering if using GAN_BERT but downloading the french version (FLAUBert) will do just as good.

**Comment by louisowen6** [comment]
Hi, in my opinion, since the role of BERT in this system is only as of the embedding generator, I think it's not a big problem if you change it to FLAUBert.

And this is the answer from the author of the original repo that answered a similar question to this:
"Hi, we didn't specifically tried the model for languages other than English. However, I think that if you use the multilingual BERT model as starting point (https://github.com/google-research/bert/blob/master/multilingual.md) you should be able to have results very similar to what we measured for the English language. You should be able to use the multilingual BERT model without any code modification."

Hope this answer helps you :)
